version: '3.9'
services:
  api:
    build:
      context: ./backend
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
